/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class demo_HelloJNIC */

#ifndef _Included_demo_HelloJNIC
#define _Included_demo_HelloJNIC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     demo_HelloJNIC
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_demo_HelloJNIC_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
