/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class demo_HelloJNICpp */

#ifndef _Included_demo_HelloJNICpp
#define _Included_demo_HelloJNICpp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     demo_HelloJNICpp
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_demo_HelloJNICpp_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
