/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class demo_HelloJNICMixCpp */

#ifndef _Included_demo_HelloJNICMixCpp
#define _Included_demo_HelloJNICMixCpp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     demo_HelloJNICMixCpp
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_demo_HelloJNICMixCpp_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
