/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TestJNIStringCpp */

#ifndef _Included_TestJNIStringCpp
#define _Included_TestJNIStringCpp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TestJNIStringCpp
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_TestJNIStringCpp_sayHello
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
